server:
  port: 9000

spring:
  application:
    name: Lucky7-PostService

  # Database
  datasource:
    query:
      jdbc-url: jdbc:mysql://${QUERY-DB-ADDRESS}:3306/moaboa
      username: ${QUERY-DB-HOST}
      password: ${QUERY-DB-PASSWORD}
    command:
      jdbc-url: jdbc:mysql://${COMMAND-DB-ADDRESS}:3306/post
      username: ${COMMAND-DB-HOST}
      password: ${COMMAND-DB-PASSWORD}
#    query:
#      jdbc-url: ${LOCAL-QUERY-DB-ADDRESS}
#      username: ${LOCAL-QUERY-DB-HOST}
#      password: ${LOCAL-QUERY-DB-PASSWORD}
#    command:
#      jdbc-url: ${LOCAL-COMMAND-DB-ADDRESS}
#      username: ${LOCAL-COMMAND-DB-HOST}
#      password: ${LOCAL-COMMAND-DB-PASSWORD}

  # JPA
  jpa:
    database-platform: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: none        # none, create, create-drop, update, validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false

#  jpa:
#    database-platform: org.mariadb.jdbc.Driver
#    hibernate:
#      ddl-auto: create        # none, create, create-drop, update, validate
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        format_sql: true
#        show_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /posts/

# Swagger
springdoc:
  swagger-ui:
    path: posts/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
  cache:
    disabled: true
  use-fqn: true
  default-consumes-media-type: application/json;charset=UTF-8